[pytest]
testpaths = scratch
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -vv --cov-report=term-missing
log_cli = true
log_cli_level = INFO
norecursedirs = .git .pytest_cache .sixth logs docs
